### ISSUE TITLE
Missing website ?

### ISSUE THREAD

**Issue by Devuno** [chisaipete/chisaipete.github.io#1]
Where did the website associated with this webpage go?
i found that the interface for the bestiary was one of the best and it would be great to have it up/accessible once more

**Comment by chisaipete** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I didn&#39;t want to play Robin Hood with copywritten content anymore: it was a personal decision to take it down permanently. There were a ton of forks before I took the repo down. I can&#39;t control what others do with the code. It was a hard decision, I liked what we had made too!</p>&mdash; Connor Petersen (@chisaipete) <a href="https://twitter.com/chisaipete/status/1164888595322114049?ref_src=twsrc%5Etfw">August 23, 2019</a></blockquote>
